// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
)

type Book struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	PublishYear sql.NullInt32  `json:"publish_year"`
	Pages       sql.NullInt32  `json:"pages"`
	Language    sql.NullString `json:"language"`
	Publisher   sql.NullString `json:"publisher"`
	Type        sql.NullString `json:"type"`
	Rating      sql.NullInt32  `json:"rating"`
	CoverUrl    sql.NullString `json:"cover_url"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}
