// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	DeleteBook(ctx context.Context, id int32) error
	GetBookByID(ctx context.Context, id int32) (Book, error)
	ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error)
	SearchBooks(ctx context.Context, arg SearchBooksParams) ([]Book, error)
}

var _ Querier = (*Queries)(nil)
